### ISSUE TITLE
2.7.0: build faiilks with enabled tests

### ISSUE THREAD

**Issue by kloczek** [intel/libva-utils#191]
```
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.0/putsurface'
Making all in test
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.0/test'
g++ -DHAVE_CONFIG_H -I. -I..    -DGTEST_HAS_PTHREAD=1 -DGTEST_USE_OWN_TR1_TUPLE=0 -DGTEST_LANG_CXX11=1 -DGTEST_HAS_TR1_TUPLE=1 -DPTHREADS -DVA_DRIVERS_PATH="\"\"" -std=c++11    -Wall -Werror -I../test/gtest/include   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -c -o test_va_api-test_va_api_fixture.o `test -f 'test_va_api_fixture.cpp' || echo './'`test_va_api_fixture.cpp
test_va_api_fixture.cpp: In constructor ‘VAAPI::VAAPIFixture::VAAPIFixture()’:
test_va_api_fixture.cpp:46:16: error: list-initializer for non-class type must not be parenthesized [-Werror]
   46 |     , m_skip("")
      |                ^
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:661: test_va_api-test_va_api_fixture.o] Error 1
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.0/test'
```

**Comment by kloczek** [comment]
The same effect on 2.7.1

**Comment by uartie** [comment]
Our internal CI isn't showing any compiler errors.  What's your compiler version?  And distro?

**Comment by uartie** [comment]
Also, does latest master compile for you?

**Comment by kloczek** [comment]
I'm using gcc 10.0.1 from rawhide.

**Comment by uartie** [comment]
fix coming

**Comment by kloczek** [comment]
https://github.com/intel/libva-utils/pull/192 is not fixing reported issue.

**Comment by uartie** [comment]
@kloczek It compiles for me on Fedora 32 + GCC 10.1.1.  What errors are you seeing now?

**Comment by kloczek** [comment]
Error still is the sam and I'm using gcc 10.1.1.
```
[tkloczko@barrel SPECS]$ rpmbuild -ba libva-utils.spec
warning: Downloading https://github.com/intel/libva-utils//commit/f5a83e63.patch#/libva-utils-test-cast-VA_STATUS_ERROR_UNKNOWN-to-VAStatus-type.patch to /home/tkloczko/rpmbuild/SOURCES/libva-utils-test-cast-VA_STATUS_ERROR_UNKNOWN-to-VAStatus-type.patch
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.bvAMwH
+ umask 022
+ cd /home/tkloczko/rpmbuild/BUILD
+ cd /home/tkloczko/rpmbuild/BUILD
+ rm -rf libva-utils-2.7.1
+ /usr/bin/gzip -dc /home/tkloczko/rpmbuild/SOURCES/libva-utils-2.7.1.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd libva-utils-2.7.1
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/libva-utils-test-cast-VA_STATUS_ERROR_UNKNOWN-to-VAStatus-type.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.s7Hs9G

[..]

g++ -DHAVE_CONFIG_H -I. -I..    -DGTEST_HAS_PTHREAD=1 -DGTEST_USE_OWN_TR1_TUPLE=0 -DGTEST_LANG_CXX11=1 -DGTEST_HAS_TR1_TUPLE=1 -DPTHREADS -DVA_DRIVERS_PATH="\"\"" -std=c++11    -Wall -Werror -I../test/gtest/include   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -fno-rtti -fno-exceptions -c -o test_va_api-test_va_api_fixture.o `test -f 'test_va_api_fixture.cpp' || echo './'`test_va_api_fixture.cpp
test_va_api_fixture.cpp: In constructor 'VAAPI::VAAPIFixture::VAAPIFixture()':
test_va_api_fixture.cpp:46:16: error: list-initializer for non-class type must not be parenthesized [-Werror]
   46 |     , m_skip("")
      |                ^
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:661: test_va_api-test_va_api_fixture.o] Error 1
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test'
make[2]: *** Waiting for unfinished jobs....
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test'
g++ -DHAVE_CONFIG_H -I. -I..    -DGTEST_HAS_PTHREAD=1 -DGTEST_USE_OWN_TR1_TUPLE=0 -DGTEST_LANG_CXX11=1 -DGTEST_HAS_TR1_TUPLE=1 -DPTHREADS -DVA_DRIVERS_PATH="\"\"" -std=c++11    -Wall -Werror -I../test/gtest/include   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -fno-rtti -fno-exceptions -c -o test_va_api-test_va_api_createcontext.o `test -f 'test_va_api_createcontext.cpp' || echo './'`test_va_api_createcontext.cpp
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test'
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test'
g++ -DHAVE_CONFIG_H -I. -I..    -DGTEST_HAS_PTHREAD=1 -DGTEST_USE_OWN_TR1_TUPLE=0 -DGTEST_LANG_CXX11=1 -DGTEST_HAS_TR1_TUPLE=1 -DPTHREADS -DVA_DRIVERS_PATH="\"\"" -std=c++11    -Wall -Werror -I../test/gtest/include   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -fno-rtti -fno-exceptions -c -o test_va_api-test_va_api_get_create_config.o `test -f 'test_va_api_get_create_config.cpp' || echo './'`test_va_api_get_create_config.cpp
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test'
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test'
g++ -DHAVE_CONFIG_H -I. -I..    -DGTEST_HAS_PTHREAD=1 -DGTEST_USE_OWN_TR1_TUPLE=0 -DGTEST_LANG_CXX11=1 -DGTEST_HAS_TR1_TUPLE=1 -DPTHREADS -DVA_DRIVERS_PATH="\"\"" -std=c++11    -Wall -Werror -I../test/gtest/include   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -fno-rtti -fno-exceptions -c -o test_va_api-test_va_api_createbuffer.o `test -f 'test_va_api_createbuffer.cpp' || echo './'`test_va_api_createbuffer.cpp
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test'
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test'
g++ -DHAVE_CONFIG_H -I. -I..    -DGTEST_HAS_PTHREAD=1 -DGTEST_USE_OWN_TR1_TUPLE=0 -DGTEST_LANG_CXX11=1 -DGTEST_HAS_TR1_TUPLE=1 -DPTHREADS -DVA_DRIVERS_PATH="\"\"" -std=c++11    -Wall -Werror -I../test/gtest/include   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -fno-rtti -fno-exceptions -c -o test_va_api-test_va_api_createsurfaces.o `test -f 'test_va_api_createsurfaces.cpp' || echo './'`test_va_api_createsurfaces.cpp
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test'
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test'
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -DGTEST_HAS_PTHREAD=1 -DGTEST_USE_OWN_TR1_TUPLE=0 -DGTEST_LANG_CXX11=1 -DGTEST_HAS_TR1_TUPLE=1 -DPTHREADS -DVA_DRIVERS_PATH="\"\"" -std=c++11   -I../test/gtest -I../test/gtest/include   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -fno-rtti -fno-exceptions -c -o gtest/src/libgtest_la-gtest-all.lo `test -f 'gtest/src/gtest-all.cc' || echo './'`gtest/src/gtest-all.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -DGTEST_HAS_PTHREAD=1 -DGTEST_USE_OWN_TR1_TUPLE=0 -DGTEST_LANG_CXX11=1 -DGTEST_HAS_TR1_TUPLE=1 -DPTHREADS -DVA_DRIVERS_PATH=\"\" -std=c++11 -I../test/gtest -I../test/gtest/include -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -fno-rtti -fno-exceptions -c gtest/src/gtest-all.cc  -fPIC -DPIC -o gtest/src/.libs/libgtest_la-gtest-all.o
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test'
make[1]: *** [Makefile:459: all-recursive] Error 1
make: *** [Makefile:391: all] Error 2
```

**Comment by kloczek** [comment]
That error only is reported when `--enable-tests` configure ioptions is used.

**Comment by uartie** [comment]
Yes, I have --enable-tests specified.

**Comment by uartie** [comment]
Did you apply both patches?

**Comment by uartie** [comment]
It looks like you only applied one of the patches

**Comment by kloczek** [comment]
Because only one is specified in in PR which closed that ticket :)
OK will check other as well.

**Comment by uartie** [comment]
5220b01a7e4c6293d5c42e6032397c4f87b09808 directly addresses (and references) the issue reported in this ticket's description.  f5a83e630e9c0d4d1621ff8da11f09017f0cdd79 addresses additional errors after fixing the aforementioned issue.  You only applied the latter commit.

**Comment by uartie** [comment]
And both patches are included in the PR.

**Comment by kloczek** [comment]
After apply second patch it compiles but test suite is failing:
```
[tkloczko@barrel SPECS]$ rpmbuild -ba libva-utils.spec
warning: Downloading https://github.com/intel/libva-utils//commit/f5a83e63.patch#/libva-utils-test-cast-VA_STATUS_ERROR_UNKNOWN-to-VAStatus-type.patch to /home/tkloczko/rpmbuild/SOURCES/libva-utils-test-cast-VA_STATUS_ERROR_UNKNOWN-to-VAStatus-type.patch
warning: Downloading https://github.com/intel/libva-utils//commit/d0a5b7f8.patch#/libva-utils-test-fixture-fix-GCC-10.0.1-error-with-drmDevicePaths.patch to /home/tkloczko/rpmbuild/SOURCES/libva-utils-test-fixture-fix-GCC-10.0.1-error-with-drmDevicePaths.patch
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.VteTMS
+ umask 022
+ cd /home/tkloczko/rpmbuild/BUILD
+ cd /home/tkloczko/rpmbuild/BUILD
+ rm -rf libva-utils-2.7.1
+ /usr/bin/gzip -dc /home/tkloczko/rpmbuild/SOURCES/libva-utils-2.7.1.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd libva-utils-2.7.1
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/libva-utils-test-cast-VA_STATUS_ERROR_UNKNOWN-to-VAStatus-type.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
+ /usr/bin/cat /home/tkloczko/rpmbuild/SOURCES/libva-utils-test-fixture-fix-GCC-10.0.1-error-with-drmDevicePaths.patch
+ /usr/bin/patch -p1 -s --fuzz=0 --no-backup-if-mismatch
+ RPM_EC=0
++ jobs -p
+ exit 0
```
```
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 check
Making check in common
make[1]: Nothing to be done for 'check'.
Making check in decode
make[1]: Nothing to be done for 'check'.
Making check in encode
make[1]: Nothing to be done for 'check'.
Making check in vainfo
make[1]: Nothing to be done for 'check'.
Making check in videoprocess
make[1]: Nothing to be done for 'check'.
Making check in vendor/intel
make[1]: Nothing to be done for 'check'.
Making check in vendor/intel/sfcsample
make[1]: Nothing to be done for 'check'.
Making check in putsurface
make[1]: Nothing to be done for 'check'.
Making check in test
/usr/bin/make  check-local
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test'
./test_va_api
[==========] Running 17415 tests from 14 test cases.
[----------] Global test environment set-up.
[----------] 1 test from VAAPIQueryVendor
[ RUN      ] VAAPIQueryVendor.NotEmpty
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
[       OK ] VAAPIQueryVendor.NotEmpty (89 ms)
[----------] 1 test from VAAPIQueryVendor (89 ms total)

[----------] 4 tests from VAAPIInitTerminate
[ RUN      ] VAAPIInitTerminate.vaInitialize_vaTerminate
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
[       OK ] VAAPIInitTerminate.vaInitialize_vaTerminate (32 ms)
[ RUN      ] VAAPIInitTerminate.vaInitialize_vaTerminate_Bad_Environment
libva info: VA-API version 1.7.0
libva info: User environment variable requested driver 'bad'
libva info: Trying to open /usr/lib64/dri/bad_drv_video.so
libva info: va_openDriver() returns -1
[       OK ] VAAPIInitTerminate.vaInitialize_vaTerminate_Bad_Environment (1 ms)
[ RUN      ] VAAPIInitTerminate.vaInitialize_vaTerminate_Bad_vaSetDriverName
libva error: vaSetDriverName returns invalid parameter
libva error: vaSetDriverName returns invalid parameter
libva info: VA-API version 1.7.0
libva info: User requested driver 'bad'
libva info: Trying to open /usr/lib64/dri/bad_drv_video.so
libva info: va_openDriver() returns -1
[       OK ] VAAPIInitTerminate.vaInitialize_vaTerminate_Bad_vaSetDriverName (1 ms)
[ RUN      ] VAAPIInitTerminate.InitTermWithoutDisplay
[       OK ] VAAPIInitTerminate.InitTermWithoutDisplay (0 ms)
[----------] 4 tests from VAAPIInitTerminate (34 ms total)

[----------] 3 tests from VAAPIGetMaxValues
[ RUN      ] VAAPIGetMaxValues.CheckMaxProfile
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
[       OK ] VAAPIGetMaxValues.CheckMaxProfile (37 ms)
[ RUN      ] VAAPIGetMaxValues.CheckMaxEntrypoints
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
[       OK ] VAAPIGetMaxValues.CheckMaxEntrypoints (39 ms)
[ RUN      ] VAAPIGetMaxValues.CheckMaxConfigAttributes
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
[       OK ] VAAPIGetMaxValues.CheckMaxConfigAttributes (49 ms)
[----------] 3 tests from VAAPIGetMaxValues (125 ms total)

[----------] 4 tests from VAAPIDisplayAttribs
[ RUN      ] VAAPIDisplayAttribs.MaxNumDisplayAttribs
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
[       OK ] VAAPIDisplayAttribs.MaxNumDisplayAttribs (42 ms)
[ RUN      ] VAAPIDisplayAttribs.QueryDisplayAttribs
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
test_va_api_display_attribs.cpp:111: Failure
Expected: (numAttribs) > (0), actual: 0 vs 0
[  FAILED  ] VAAPIDisplayAttribs.QueryDisplayAttribs (49 ms)
[ RUN      ] VAAPIDisplayAttribs.GetDisplayAttribs
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
test_va_api_display_attribs.cpp:132: Failure
Expected: (numAttribs) > (0), actual: 0 vs 0
[  FAILED  ] VAAPIDisplayAttribs.GetDisplayAttribs (45 ms)
[ RUN      ] VAAPIDisplayAttribs.SetDisplayAttribs
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
test_va_api_display_attribs.cpp:165: Failure
Expected: (numAttribs) > (0), actual: 0 vs 0
[  FAILED  ] VAAPIDisplayAttribs.SetDisplayAttribs (51 ms)
[----------] 4 tests from VAAPIDisplayAttribs (187 ms total)

[----------] 1 test from VAAPICreateContextToFail
[ RUN      ] VAAPICreateContextToFail.CreateContextWithNoConfig
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
make[2]: *** [Makefile:1086: check-local] Segmentation fault (core dumped)
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test'
make[1]: *** [Makefile:927: check-am] Error 2
make: *** [Makefile:459: check-recursive] Error 1
```

**Comment by uartie** [comment]
The failure looks like a "nouveau" driver problem.  Please file a bug with them.  All tests pass with i965 and iHD drivers.

**Comment by kloczek** [comment]
```
[tkloczko@barrel SPECS]$ coredumpctl | grep libva-utils
Wed 2020-05-13 18:32:43 BST  3307604  1000  1000  11 present   /home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test/test_va_api
[tkloczko@barrel SPECS]$ coredumpctl gdb 3307604
           PID: 3307604 (test_va_api)
           UID: 1000 (tkloczko)
           GID: 1000 (tkloczko)
        Signal: 11 (SEGV)
     Timestamp: Wed 2020-05-13 18:32:43 BST (2min 53s ago)
  Command Line: ./test_va_api
    Executable: /home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test/test_va_api
 Control Group: /user.slice/user-1000.slice/session-83.scope
          Unit: session-83.scope
         Slice: user-1000.slice
       Session: 83
     Owner UID: 1000 (tkloczko)
       Boot ID: 96324d359f1e4902844be60b659793a6
    Machine ID: d033f66b249a4ec09acfa81ac205554f
      Hostname: barrel
       Storage: /var/lib/systemd/coredump/core.test_va_api.1000.96324d359f1e4902844be60b659793a6.3307604.1589391163000000000000.lz4
       Message: Process 3307604 (test_va_api) of user 1000 dumped core.

                Stack trace of thread 3307604:
                #0  0x00007fe762c93d6e vlVaCreateContext (nouveau_drv_video.so + 0xa5d6e)
                #1  0x00007fe76395c397 vaCreateContext (libva.so.2 + 0x18397)
                #2  0x000055bb05b1a419 n/a (/home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test/test_va_api + 0x4e419)

GNU gdb (GDB) Fedora 9.0.50.20191119-2.fc32
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/tkloczko/rpmbuild/BUILD/libva-utils-2.7.1/test/test_va_api...
[New LWP 3307604]
[New LWP 3307641]
[New LWP 3307642]
[New LWP 3307644]
[New LWP 3307643]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./test_va_api'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  vlVaCreateContext (ctx=<optimized out>, config_id=4294967295, picture_width=1920, picture_height=1080, flag=1, render_targets=0x0, num_render_targets=0, context_id=0x55bb07ee4748)
    at ../src/gallium/state_trackers/va/context.c:229
229        is_vpp = config->profile == PIPE_VIDEO_PROFILE_UNKNOWN && !picture_width &&
[Current thread is 1 (Thread 0x7fe7635b3380 (LWP 3307604))]
 elfutils-libelf-0.179-3.fc33.x86_64 expat-2.2.9-2.1.fc32.x86_64 glibc-2.31.9000-12.fc33.x86_64 libX11-1.6.9-4.fc32.x86_64 libX11-xcb-1.6.9-4.fc32.x86_64 libXau-1.0.9-4.fc32.x86_64 libXdmcp-1.1.3-4.fc32.x86_64 libdrm-2.4.101-2.fc33.x86_64 libedit-3.1-33.20191231cvs.fc33.x86_64 libffi-3.2.1-2.3.fc32.x86_64 libgcc-10.1.1-1.fc33.x86_64 libstdc++-10.1.1-1.fc33.x86_64 libva-2.7.1-2.fc33.x86_64 libxcb-1.14-5.fc33.x86_64 libxshmfence-1.3-7.fc32.x86_64 libzstd-1.4.4-3.fc33.x86_64 llvm-libs-10.0.0-2.fc33.x86_64 sssd-client-2.2.3-14.fc33.x86_64 zlib-1.2.11-22.fc33.x86_64
(gdb) bt full
Missing separate debuginfos, use: dnf debuginfo-install#0  vlVaCreateContext (ctx=<optimized out>, config_id=4294967295, picture_width=1920, picture_height=1080, flag=1, render_targets=0x0, num_render_targets=0, context_id=0x55bb07ee4748)
    at ../src/gallium/state_trackers/va/context.c:229
        drv = 0x55bb07f0a9f0
        context = <optimized out>
        config = 0x0
        is_vpp = <optimized out>
#1  0x00007fe76395c397 in vaCreateContext () from /lib64/libva.so.2
No symbol table info available.
#2  0x000055bb05b1a419 in VAAPI::VAAPIFixture::doCreateContext (this=<optimized out>, resolution=..., expectation=@0x7ffd45518cf8: 4) at test_va_api_fixture.cpp:436
        gtest_ar = {success_ = false, message_ = {ptr_ = 0x4a7ecdeeefd76700}}
#3  0x000055bb05b1ed34 in VAAPI::VAAPICreateContextToFail_CreateContextWithNoConfig_Test::TestBody (this=0x55bb07ee4720) at test_utils.h:36
No locals.
#4  0x000055bb05b16e23 in testing::Test::Run (this=0x55bb07ee4720) at ../test/gtest/src/gtest.cc:2474
        impl = 0x55bb07484f60
        impl = <optimized out>
#5  testing::Test::Run (this=0x55bb07ee4720) at ../test/gtest/src/gtest.cc:2465
        impl = <optimized out>
        impl = <optimized out>
#6  testing::TestInfo::Run (this=0x55bb07489e00) at ../test/gtest/src/gtest.cc:2656
        impl = 0x55bb07484f60
        repeater = 0x55bb07484dd0
        start = 1589391163103
        test = 0x55bb07ee4720
        impl = <optimized out>
        repeater = <optimized out>
        start = <optimized out>
        test = <optimized out>
#7  testing::TestInfo::Run (this=0x55bb07489e00) at ../test/gtest/src/gtest.cc:2630
        impl = <optimized out>
        repeater = <optimized out>
        start = <optimized out>
        test = <optimized out>
        impl = <optimized out>
        repeater = <optimized out>
        start = <optimized out>
        test = <optimized out>
#8  testing::TestCase::Run (this=0x55bb0748c7d0) at ../test/gtest/src/gtest.cc:2774
        i = 0
        impl = 0x55bb07484f60
        repeater = 0x55bb07484dd0
        start = 1589391163103
        impl = <optimized out>
        repeater = <optimized out>
        start = <optimized out>
        i = <optimized out>
#9  testing::TestCase::Run (this=0x55bb0748c7d0) at ../test/gtest/src/gtest.cc:2759
        impl = <optimized out>
        repeater = <optimized out>
        start = <optimized out>
        impl = <optimized out>
        repeater = <optimized out>
        start = <optimized out>
        i = <optimized out>
#10 testing::internal::UnitTestImpl::RunAllTests (this=<optimized out>) at ../test/gtest/src/gtest.cc:4649
        test_index = 4
        start = 1589391162668
        i = 0
        should_shard = <optimized out>
        has_tests_to_run = true
        repeater = 0x55bb07484dd0
        forever = <optimized out>
        in_subprocess_for_death_test = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        failed = false
        repeat = <optimized out>
        in_subprocess_for_death_test = <optimized out>
        should_shard = <optimized out>
        has_tests_to_run = <optimized out>
        failed = <optimized out>
        repeater = <optimized out>
        repeat = <optimized out>
        forever = <optimized out>
        i = <optimized out>
        start = <optimized out>
        test_index = <optimized out>
#11 testing::internal::UnitTestImpl::RunAllTests (this=<optimized out>) at ../test/gtest/src/gtest.cc:4551
        in_subprocess_for_death_test = <optimized out>
        should_shard = <optimized out>
        has_tests_to_run = <optimized out>
        failed = <optimized out>
        repeater = <optimized out>
        repeat = <optimized out>
        forever = <optimized out>
        i = <optimized out>
        start = <optimized out>
        test_index = <optimized out>
#12 0x000055bb05ae5179 in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=<synthetic pointer>,
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x55bb05b15c20 <testing::internal::UnitTestImpl::RunAllTests()>, object=0x55bb07484f60)
    at ../test/gtest/src/gtest.cc:2410
No locals.
#13 testing::UnitTest::Run (this=0x55bb05b3b340 <testing::UnitTest::GetInstance()::instance>) at ../test/gtest/src/gtest.cc:4257
        in_death_test_child_process = <optimized out>
        premature_exit_file = <optimized out>
        in_death_test_child_process = <optimized out>
        premature_exit_file = <optimized out>
#14 RUN_ALL_TESTS () at ../test/gtest/include/gtest/gtest.h:2233
No locals.
#15 main (argc=<optimized out>, argv=0x7ffd45519028) at test_main.cpp:31
No locals.
(gdb)
```

But I think thaty this issue ius related to the mesa issue which I've already reported in mesa which is alredy identified as the bug
https://gitlab.freedesktop.org/mesa/mesa/-/issues/2863

**Comment by kloczek** [comment]
No that one looks like something new but still seems you are right that it is not libva-utils bug :)

**Comment by uartie** [comment]
Either way, it's unrelated to the issue reported herewithin.  Thanks for reporting compile issues and testing that #192 fixes them.
