### ISSUE TITLE
2.9.0: test suite is code dumping

### ISSUE THREAD

**Issue by kloczek** [intel/libva-utils#198]
I've started building with installed libva 2.8.0.
Going to check is it will be core dumping when will upgrade to libva 2.9.0 and if it will be OK it will mean that in libva-utils configure.ac should be bumpued minimum version.
```
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 check
Making check in common
make[1]: Nothing to be done for 'check'.
Making check in decode
make[1]: Nothing to be done for 'check'.
Making check in encode
make[1]: Nothing to be done for 'check'.
Making check in vainfo
make[1]: Nothing to be done for 'check'.
Making check in videoprocess
make[1]: Nothing to be done for 'check'.
Making check in vendor/intel
make[1]: Nothing to be done for 'check'.
Making check in vendor/intel/sfcsample
make[1]: Nothing to be done for 'check'.
Making check in putsurface
make[1]: Nothing to be done for 'check'.
Making check in test
/usr/bin/make  check-local
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.9.0/test'
./test_va_api
[==========] Running 17415 tests from 14 test cases.
[----------] Global test environment set-up.
[----------] 1 test from VAAPIQueryVendor
[ RUN      ] VAAPIQueryVendor.NotEmpty
libva info: VA-API version 1.8.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
[       OK ] VAAPIQueryVendor.NotEmpty (79 ms)
[----------] 1 test from VAAPIQueryVendor (79 ms total)

[----------] 4 tests from VAAPIInitTerminate
[ RUN      ] VAAPIInitTerminate.vaInitialize_vaTerminate
libva info: VA-API version 1.8.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
[       OK ] VAAPIInitTerminate.vaInitialize_vaTerminate (45 ms)
[ RUN      ] VAAPIInitTerminate.vaInitialize_vaTerminate_Bad_Environment
libva info: VA-API version 1.8.0
libva info: User environment variable requested driver 'bad'
libva info: Trying to open /usr/lib64/dri/bad_drv_video.so
libva info: va_openDriver() returns -1
[       OK ] VAAPIInitTerminate.vaInitialize_vaTerminate_Bad_Environment (0 ms)
[ RUN      ] VAAPIInitTerminate.vaInitialize_vaTerminate_Bad_vaSetDriverName
libva error: vaSetDriverName returns invalid parameter
libva error: vaSetDriverName returns invalid parameter
libva info: VA-API version 1.8.0
libva info: User requested driver 'bad'
libva info: Trying to open /usr/lib64/dri/bad_drv_video.so
libva info: va_openDriver() returns -1
[       OK ] VAAPIInitTerminate.vaInitialize_vaTerminate_Bad_vaSetDriverName (1 ms)
[ RUN      ] VAAPIInitTerminate.InitTermWithoutDisplay
[       OK ] VAAPIInitTerminate.InitTermWithoutDisplay (0 ms)
[----------] 4 tests from VAAPIInitTerminate (46 ms total)

[----------] 3 tests from VAAPIGetMaxValues
[ RUN      ] VAAPIGetMaxValues.CheckMaxProfile
libva info: VA-API version 1.8.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
[       OK ] VAAPIGetMaxValues.CheckMaxProfile (39 ms)
[ RUN      ] VAAPIGetMaxValues.CheckMaxEntrypoints
libva info: VA-API version 1.8.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
[       OK ] VAAPIGetMaxValues.CheckMaxEntrypoints (35 ms)
[ RUN      ] VAAPIGetMaxValues.CheckMaxConfigAttributes
libva info: VA-API version 1.8.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
[       OK ] VAAPIGetMaxValues.CheckMaxConfigAttributes (32 ms)
[----------] 3 tests from VAAPIGetMaxValues (106 ms total)

[----------] 4 tests from VAAPIDisplayAttribs
[ RUN      ] VAAPIDisplayAttribs.MaxNumDisplayAttribs
libva info: VA-API version 1.8.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
[       OK ] VAAPIDisplayAttribs.MaxNumDisplayAttribs (32 ms)
[ RUN      ] VAAPIDisplayAttribs.QueryDisplayAttribs
libva info: VA-API version 1.8.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
test_va_api_display_attribs.cpp:111: Failure
Expected: (numAttribs) > (0), actual: 0 vs 0
[  FAILED  ] VAAPIDisplayAttribs.QueryDisplayAttribs (26 ms)
[ RUN      ] VAAPIDisplayAttribs.GetDisplayAttribs
libva info: VA-API version 1.8.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
test_va_api_display_attribs.cpp:132: Failure
Expected: (numAttribs) > (0), actual: 0 vs 0
[  FAILED  ] VAAPIDisplayAttribs.GetDisplayAttribs (34 ms)
[ RUN      ] VAAPIDisplayAttribs.SetDisplayAttribs
libva info: VA-API version 1.8.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
test_va_api_display_attribs.cpp:165: Failure
Expected: (numAttribs) > (0), actual: 0 vs 0
[  FAILED  ] VAAPIDisplayAttribs.SetDisplayAttribs (26 ms)
[----------] 4 tests from VAAPIDisplayAttribs (118 ms total)

[----------] 1 test from VAAPICreateContextToFail
[ RUN      ] VAAPICreateContextToFail.CreateContextWithNoConfig
libva info: VA-API version 1.8.0
libva info: Trying to open /usr/lib64/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_8
libva info: va_openDriver() returns 0
make[2]: *** [Makefile:1086: check-local] Segmentation fault (core dumped)
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libva-utils-2.9.0/test'
make[1]: *** [Makefile:927: check-am] Error 2
make: *** [Makefile:459: check-recursive] Error 1
```
```
[tkloczko@barrel SPECS]$ coredumpctl gdb 3887182
           PID: 3887182 (test_va_api)
           UID: 1000 (tkloczko)
           GID: 1000 (tkloczko)
        Signal: 11 (SEGV)
     Timestamp: Sun 2020-09-13 18:20:44 BST (16min ago)
  Command Line: ./test_va_api
    Executable: /home/tkloczko/rpmbuild/BUILD/libva-utils-2.9.0/test/test_va_api
 Control Group: /user.slice/user-1000.slice/session-297.scope
          Unit: session-297.scope
         Slice: user-1000.slice
       Session: 297
     Owner UID: 1000 (tkloczko)
       Boot ID: ab9d350c623e4313bacb892de46b85f9
    Machine ID: d033f66b249a4ec09acfa81ac205554f
      Hostname: barrel
       Storage: /var/lib/systemd/coredump/core.test_va_api.1000.ab9d350c623e4313bacb892de46b85f9.3887182.1600017644000000.zst
       Message: Process 3887182 (test_va_api) of user 1000 dumped core.

                Stack trace of thread 3887182:
                #0  0x00007fa88b2cc6d2 vlVaCreateContext.cold (nouveau_drv_video.so + 0xb16d2)
                #1  0x00007fa88c1fd447 vaCreateContext (libva.so.2 + 0x18447)
                #2  0x0000555ddf637419 n/a (/home/tkloczko/rpmbuild/BUILD/libva-utils-2.9.0/test/test_va_api + 0x4e419)

GNU gdb (GDB) Fedora 9.0.50.20191119-2.fc32
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/tkloczko/rpmbuild/BUILD/libva-utils-2.9.0/test/test_va_api...
[New LWP 3887182]
[New LWP 3887221]
[New LWP 3887220]
[New LWP 3887222]
[New LWP 3887223]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./test_va_api'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  vlVaCreateContext (ctx=<optimized out>, config_id=4294967295, picture_width=1920, picture_height=1080, flag=1, render_targets=0x0, num_render_targets=0, context_id=0x555de09b7198)
    at ../src/gallium/state_trackers/va/context.c:229
229     ../src/gallium/state_trackers/va/context.c: No such file or directory.
[Current thread is 1 (Thread 0x7fa88bc904c0 (LWP 3887182))]
 elfutils-libelf-0.181-2.fc34.x86_64 expat-2.2.9-2.2.fc34.x86_64 glibc-2.32.9000-5.fc34.x86_64 gmp-6.2.0-5.fc33.x86_64 libX11-1.6.12-2.fc34.x86_64 libX11-xcb-1.6.12-2.fc34.x86_64 libXau-1.0.9-5.fc33.x86_64 libXdmcp-1.1.3-5.fc33.x86_64 libdrm-2.4.102-3.fc34.x86_64 libedit-3.1-34.20191231cvs.fc34.x86_64 libffi-3.2.1-2.3.fc32.x86_64 libgcc-10.2.1-3.fc34.x86_64 libstdc++-10.2.1-3.fc34.x86_64 libva-2.8.0-3.fc34.x86_64 libxcb-1.14-6.fc34.x86_64 libxml2-2.9.10-8.fc34.x86_64 libxshmfence-1.3-8.fc33.x86_64 libzstd-1.4.5-7.fc34.x86_64 llvm-libs-10.0.1-2.1.fc34.x86_64 ncurses-libs-6.2-4.20200817.fc34.x86_64 sssd-client-2.3.0-2.fc33.x86_64 xz-libs-5.2.5-4.fc33.x86_64 z3-libs-4.8.8-5.fc33.x86_64 zlib-1.2.11-23.fc33.x86_64
(gdb) bt full
Missing separate debuginfos, use: dnf debuginfo-install#0  vlVaCreateContext (ctx=<optimized out>, config_id=4294967295, picture_width=1920, picture_height=1080, flag=1, render_targets=0x0, num_render_targets=0, context_id=0x555de09b7198)
    at ../src/gallium/state_trackers/va/context.c:229
        drv = 0x555de09ef2e0
        context = <optimized out>
        config = 0x0
        is_vpp = <optimized out>
#1  0x00007fa88c1fd447 in vaCreateContext () from /lib64/libva.so.2
No symbol table info available.
#2  0x0000555ddf637419 in VAAPI::VAAPIFixture::doCreateContext (this=<optimized out>, resolution=..., expectation=@0x7ffc40510978: 4) at test_va_api_fixture.cpp:436
        gtest_ar = {success_ = 32, message_ = {ptr_ = 0xa23a335dbbcdf400}}
#3  0x0000555ddf63bd34 in VAAPI::VAAPICreateContextToFail_CreateContextWithNoConfig_Test::TestBody (this=0x555de09b7170) at test_utils.h:36
No locals.
#4  0x0000555ddf633e23 in testing::Test::Run (this=0x555de09b7170) at ../test/gtest/src/gtest.cc:2474
        impl = 0x555ddffbbf60
        impl = <optimized out>
#5  testing::Test::Run (this=0x555de09b7170) at ../test/gtest/src/gtest.cc:2465
        impl = <optimized out>
        impl = <optimized out>
#6  testing::TestInfo::Run (this=0x555ddffc0e00) at ../test/gtest/src/gtest.cc:2656
        impl = 0x555ddffbbf60
        repeater = 0x555ddffbbdd0
        start = 1600017644697
        test = 0x555de09b7170
        impl = <optimized out>
        repeater = <optimized out>
        start = <optimized out>
        test = <optimized out>
#7  testing::TestInfo::Run (this=0x555ddffc0e00) at ../test/gtest/src/gtest.cc:2630
        impl = <optimized out>
        repeater = <optimized out>
        start = <optimized out>
        test = <optimized out>
        impl = <optimized out>
        repeater = <optimized out>
        start = <optimized out>
        test = <optimized out>
#8  testing::TestCase::Run (this=0x555ddffc37d0) at ../test/gtest/src/gtest.cc:2774
        i = 0
        impl = 0x555ddffbbf60
        repeater = 0x555ddffbbdd0
        start = 1600017644697
        impl = <optimized out>
        repeater = <optimized out>
        start = <optimized out>
        i = <optimized out>
#9  testing::TestCase::Run (this=0x555ddffc37d0) at ../test/gtest/src/gtest.cc:2759
        impl = <optimized out>
        repeater = <optimized out>
        start = <optimized out>
        impl = <optimized out>
        repeater = <optimized out>
        start = <optimized out>
        i = <optimized out>
#10 testing::internal::UnitTestImpl::RunAllTests (this=<optimized out>) at ../test/gtest/src/gtest.cc:4649
        test_index = 4
        start = 1600017644348
        i = 0
        should_shard = <optimized out>
        has_tests_to_run = true
        repeater = 0x555ddffbbdd0
        forever = <optimized out>
        in_subprocess_for_death_test = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        failed = false
        repeat = <optimized out>
        in_subprocess_for_death_test = <optimized out>
        should_shard = <optimized out>
        has_tests_to_run = <optimized out>
        failed = <optimized out>
        repeater = <optimized out>
        repeat = <optimized out>
        forever = <optimized out>
        i = <optimized out>
        start = <optimized out>
        test_index = <optimized out>
#11 testing::internal::UnitTestImpl::RunAllTests (this=<optimized out>) at ../test/gtest/src/gtest.cc:4551
        in_subprocess_for_death_test = <optimized out>
        should_shard = <optimized out>
        has_tests_to_run = <optimized out>
        failed = <optimized out>
        repeater = <optimized out>
        repeat = <optimized out>
        forever = <optimized out>
        i = <optimized out>
        start = <optimized out>
        test_index = <optimized out>
#12 0x0000555ddf602179 in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=<synthetic pointer>,
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x555ddf632c20 <testing::internal::UnitTestImpl::RunAllTests()>, object=0x555ddffbbf60)
    at ../test/gtest/src/gtest.cc:2410
No locals.
#13 testing::UnitTest::Run (this=0x555ddf658340 <testing::UnitTest::GetInstance()::instance>) at ../test/gtest/src/gtest.cc:4257
        in_death_test_child_process = <optimized out>
        premature_exit_file = <optimized out>
        in_death_test_child_process = <optimized out>
        premature_exit_file = <optimized out>
#14 RUN_ALL_TESTS () at ../test/gtest/include/gtest/gtest.h:2233
No locals.
#15 main (argc=<optimized out>, argv=0x7ffc40510ca8) at test_main.cpp:31
No locals.
(gdb)
```

**Comment by kloczek** [comment]
Nope. Upgrade libva 2.9.0 did not help.
Still sore dumps in:
```
    at ../src/gallium/state_trackers/va/context.c:229
```

**Comment by kloczek** [comment]
One sec .. looks like it crashes in nouveau mesa driver?
Am I right?

**Comment by XinfengZhang** [comment]
yes

**Comment by kloczek** [comment]
OK so I'm closing this issue ticket.

Thx :)
