### ISSUE TITLE
Failed tests on Intel Alderlake

### ISSUE THREAD

**Issue by stolk** [intel/libva-utils#282]
Running `./test_va_api` on my Alderlake CPU/GPU i5-12600k gives me 22 failed tests:
```
...
[==========] 17415 tests from 14 test suites ran. (6280 ms total)
[  PASSED  ] 17393 tests.
[  FAILED  ] 22 tests, listed below:
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/136, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 16x16)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/137, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 32x32)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/138, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 176x120)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/139, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 352x240)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/140, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 352x288)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/141, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 480x320)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/142, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 720x480)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/143, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 720x576)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/144, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 768x576)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/145, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 800x480)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/146, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 854x480)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/147, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 1280x720)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/148, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 1920x1080)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/149, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 2048x1080)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/150, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 4096x2160)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/151, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 8192x8192)
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/152, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 10240x10240)
[  FAILED  ] CreateBuffer/VAAPICreateBuffer.CreateBufferWithOutData/352, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 41:VAProcPipelineParameterBufferType, 224)
[  FAILED  ] CreateBuffer/VAAPICreateBuffer.CreateBufferWithOutData/353, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 42:VAProcFilterParameterBufferType, 24)
[  FAILED  ] CreateBuffer/VAAPICreateBuffer.CreateBufferWithOutData/354, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 42:VAProcFilterParameterBufferType, 28)
[  FAILED  ] CreateBuffer/VAAPICreateBuffer.CreateBufferWithOutData/355, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 42:VAProcFilterParameterBufferType, 28)
[  FAILED  ] CreateBuffer/VAAPICreateBuffer.CreateBufferWithOutData/356, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 42:VAProcFilterParameterBufferType, 12)

22 FAILED TESTS
```

The vainfo tool returns:
```
$ vainfo/vainfo 
libva info: VA-API version 1.15.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.15 (libva 2.15.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.4.3 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain12             :	VAEntrypointVLD
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain422_12         :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointVLD
      VAProfileHEVCSccMain            :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          :	VAEntrypointVLD
      VAProfileHEVCSccMain10          :	VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         :	VAEntrypointVLD
      VAProfileHEVCSccMain444         :	VAEntrypointEncSliceLP
      VAProfileAV1Profile0            :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointEncSliceLP
```

The [installed driver](https://packages.ubuntu.com/kinetic/intel-media-va-driver):
```
ii  intel-media-va-driver:amd64                22.4.3+dfsg1-1                           amd64        VAAPI driver for the Intel GEN8+ Graphics family
```

output from the first failed test:
```
[ RUN      ] CreateContext/VAAPICreateContext.CreateContext/136
libva info: VA-API version 1.15.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
test_va_api_fixture.cpp:454: Failure
Expected equality of these values:
  VaapiStatus(expectation)
    Which is: VA_STATUS_SUCCESS
  VaapiStatus(vaCreateContext(m_vaDisplay, m_configID, resolution.width, resolution.height, 0x1, __null, 0, &m_contextID))
    Which is: VA_STATUS_ERROR_UNKNOWN
Google Test trace:
test_va_api_createcontext.cpp:95: resolution: min=16x16; max=16384x16384; current=16x16
test_va_api_fixture.cpp:462: Failure
Expected equality of these values:
  VaapiStatus(expectation)
    Which is: VA_STATUS_SUCCESS
  VaapiStatus(vaDestroyContext(m_vaDisplay, m_contextID))
    Which is: VA_STATUS_ERROR_INVALID_CONTEXT
Google Test trace:
test_va_api_createcontext.cpp:95: resolution: min=16x16; max=16384x16384; current=16x16
[  FAILED  ] CreateContext/VAAPICreateContext.CreateContext/136, where GetParam() = (-1:VAProfileNone, 10:VAEntrypointVideoProc, 16x16) (3 ms)
```

Is this test expected to fail on Alderlake?

**Comment by uartie** [comment]
These passed on my ADL using latest driver master branch.

**Comment by Sherry-Lin** [comment]
This case is also passed on our regular cycles. Could you try with latest release tag? What's the kernel version you are using?

**Comment by stolk** [comment]
kernel: 5.19.0-15-generic

And sorry, this actually was with the released version: https://github.com/intel/libva-utils/releases/tag/2.15.0

I will try with latest in git as well...

**Comment by stolk** [comment]
Ok, I tried building libva / libgmm / media driver from git source, and getting different results:

Worryingly, some tests take far too long:

```
[ RUN      ] CreateSurfaces/VAAPICreateSurfaces.CreateSurfacesWithConfigAttribs/151
[       OK ] CreateSurfaces/VAAPICreateSurfaces.CreateSurfacesWithConfigAttribs/151 (61620 ms)
```

I'll do some further digging and see what I can find.

**Comment by stolk** [comment]
So when building all from current git (libva, gmmlib, media-driver, libva-utils) the tests all pass.
But I noticed it is quite slow. Is the test supposed to take this long? (25 minutes.)
```
[----------] Global test environment tear-down
[==========] 17415 tests from 14 test suites ran. (1506134 ms total)
[  PASSED  ] 17415 tests.
```

**Comment by uartie** [comment]
25 mins is way too long!

I just looked at the duration statistics on our CI and see that all platforms used to take ~2-5 minutes.  But sometime after July 25 they started to take 18 minutes or more!

This could be a definite red-flag and needs to be investigated.

**Comment by uartie** [comment]
@Sherry-Lin can you delegate someone to look into this performance problem?  It's likely caused by some change in the driver and could be impacting normal driver usage.

**Comment by uartie** [comment]
According to our CI, https://github.com/intel/media-driver/commit/bffd62a2e6f8 was the last known commit where the tests were fast on all platforms.  And in our next CI test run, when tests started taking a long time, the only change detected occurred in the driver.

**Comment by stolk** [comment]
In case it helps, if I interrupt a slow test, I get this callstack:
```
#0  __GI___ioctl (fd=fd@entry=3, request=request@entry=1074553951) at ../sysdeps/unix/sysv/linux/ioctl.c:36
#1  0x00007ffff7e5b7b0 in drmIoctl (fd=3, request=1074553951, arg=0x7fffffffd550) at ../xf86drm.c:630
#2  0x00007ffff39b95e6 in mos_gem_bo_start_gtt_access (bo=0x55555613efb0, write_enable=1)
    at /home/stolk/src/media-driver/media_driver/linux/common/os/i915/mos_bufmgr.c:2468
#3  0x00007ffff39b932d in mos_gem_bo_wait_rendering (bo=0x55555613efb0) at /home/stolk/src/media-driver/media_driver/linux/common/os/i915/mos_bufmgr.c:2377
#4  0x00007ffff39b751c in mos_gem_bo_free (bo=0x55555613efb0) at /home/stolk/src/media-driver/media_driver/linux/common/os/i915/mos_bufmgr.c:1570
#5  0x00007ffff39b7a91 in mos_gem_bo_unreference_final (bo=0x55555613efb0, time=111238) at /home/stolk/src/media-driver/media_driver/linux/common/os/i915/mos_bufmgr.c:1702
#6  0x00007ffff39b7bf6 in mos_gem_bo_unreference (bo=0x55555613efb0) at /home/stolk/src/media-driver/media_driver/linux/common/os/i915/mos_bufmgr.c:1732
#7  0x00007ffff39b410a in mos_bo_unreference (bo=0x55555613efb0) at /home/stolk/src/media-driver/media_driver/linux/common/os/i915/mos_bufmgr_api.c:120
#8  0x00007ffff40358d0 in DdiMediaUtil_FreeSurface (surface=0x55555613e850) at /home/stolk/src/media-driver/media_driver/linux/common/ddi/media_libva_util.cpp:1497
#9  0x00007ffff40016f5 in DdiMedia_DestroySurfaces (ctx=0x555556114000, surfaces=0x55555613bcb0, num_surfaces=10)
    at /home/stolk/src/media-driver/media_driver/linux/common/ddi/media_libva.cpp:2580
#10 0x00007ffff7f905c2 in vaDestroySurfaces (dpy=0x55555609ca40, surface_list=0x55555613bcb0, num_surfaces=10) at ../../va/va.c:1217
#11 0x000055555557cc54 in VAAPI::VAAPIFixture::destroySurfaces (this=<optimized out>, surfaces=std::vector of length 10, capacity 10 = {...})
    at ../../test/test_va_api_fixture.cpp:427
#12 0x0000555555598022 in operator() (attribs=std::vector of length 1, capacity 1 = {...}, __closure=0x7fffffffd960) at ../../test/test_va_api_createsurfaces.cpp:215
#13 std::__invoke_impl<void, VAAPI::VAAPICreateSurfaces_CreateSurfacesWithConfigAttribs_Test::TestBody()::<lambda(const VAAPI::SurfaceAttributes&)>&, const std::vector<_VASurfaceAttrib, std::allocator<_VASurfaceAttrib> >&> (__f=...) at /usr/include/c++/12/bits/invoke.h:61
#14 std::__invoke_r<void, VAAPI::VAAPICreateSurfaces_CreateSurfacesWithConfigAttribs_Test::TestBody()::<lambda(const VAAPI::SurfaceAttributes&)>&, const std::vector<_VASurfaceAttrib, std::allocator<_VASurfaceAttrib> >&> (__fn=...) at /usr/include/c++/12/bits/invoke.h:154
#15 std::_Function_handler<void(const std::vector<_VASurfaceAttrib, std::allocator<_VASurfaceAttrib> >&), VAAPI::VAAPICreateSurfaces_CreateSurfacesWithConfigAttribs_Test::TestBody()::<lambda(const VAAPI::SurfaceAttributes&)> >::_M_invoke(const std::_Any_data &, const std::vector<_VASurfaceAttrib, std::allocator<_VASurfaceAttrib> > &) (
    __functor=..., __args#0=std::vector of length 1, capacity 1 = {...}) at /usr/include/c++/12/bits/std_function.h:290
#16 0x000055555559e302 in std::function<void (std::vector<_VASurfaceAttrib, std::allocator<_VASurfaceAttrib> > const&)>::operator()(std::vector<_VASurfaceAttrib, std::allocator<_VASurfaceAttrib> > const&) const (__args#0=std::vector of length 1, capacity 1 = {...}, this=0x7fffffffd960) at /usr/include/c++/12/bits/std_function.h:591
#17 VAAPI::VAAPISurfaceFixture::testWithSupportedSurfaceAttributes(std::function<void (std::vector<_VASurfaceAttrib, std::allocator<_VASurfaceAttrib> > const&)> const&) (
    this=<optimized out>, test=...) at ../../test/test_va_api_createsurfaces.cpp:126
#18 0x00005555555991c9 in operator() (attribs=..., __closure=0x555555f977e0) at ../../test/test_va_api_createsurfaces.cpp:226
#19 std::__invoke_impl<void, VAAPI::VAAPICreateSurfaces_CreateSurfacesWithConfigAttribs_Test::TestBody()::<lambda(const VAAPI::ConfigAttributes&)>&, const std::vector<_VAConfigAttrib, std::allocator<_VAConfigAttrib> >&> (__f=...) at /usr/include/c++/12/bits/invoke.h:61
#20 std::__invoke_r<void, VAAPI::VAAPICreateSurfaces_CreateSurfacesWithConfigAttribs_Test::TestBody()::<lambda(const VAAPI::ConfigAttributes&)>&, const std::vector<_VAConfigAttrib, std::allocator<_VAConfigAttrib> >&> (__fn=...) at /usr/include/c++/12/bits/invoke.h:154
#21 std::_Function_handler<void(const std::vector<_VAConfigAttrib, std::allocator<_VAConfigAttrib> >&), VAAPI::VAAPICreateSurfaces_CreateSurfacesWithConfigAttribs_Test::TestBody()::<lambda(const VAAPI::ConfigAttributes&)> >::_M_invoke(const std::_Any_data &, const std::vector<_VAConfigAttrib, std::allocator<_VAConfigAttrib> > &) (
    __functor=..., __args#0=...) at /usr/include/c++/12/bits/std_function.h:290
#22 0x000055555559bbd0 in std::function<void (std::vector<_VAConfigAttrib, std::allocator<_VAConfigAttrib> > const&)>::operator()(std::vector<_VAConfigAttrib, std::allocator<_VAConfigAttrib> > const&) const (__args#0=std::vector of length 1, capacity 1 = {...}, this=0x7fffffffdab0) at /usr/include/c++/12/bits/std_function.h:591
#23 VAAPI::VAAPISurfaceFixture::testWithSupportedConfigAttributes(std::function<void (std::vector<_VAConfigAttrib, std::allocator<_VAConfigAttrib> > const&)> const&) (
    this=this@entry=0x5555561ca2f8, test=...) at ../../test/test_va_api_createsurfaces.cpp:68
#24 0x0000555555598607 in VAAPI::VAAPICreateSurfaces_CreateSurfacesWithConfigAttribs_Test::TestBody (this=0x5555561ca2f0) at ../../test/test_va_api_createsurfaces.cpp:232
#25 0x00005555555ed0ff in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (location=0x5555555f6179 "the test body", method=<optimized out>, 
    object=0x5555561ca2f8) at ../../test/gtest/src/gtest.cc:2607
#26 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=object@entry=0x5555561ca2f8, method=<optimized out>, 
    location=location@entry=0x5555555f6179 "the test body") at ../../test/gtest/src/gtest.cc:2643
#27 0x00005555555ddbd6 in testing::Test::Run (this=0x5555561ca2f8) at ../../test/gtest/src/gtest.cc:2682
#28 testing::Test::Run (this=0x5555561ca2f8) at ../../test/gtest/src/gtest.cc:2672
#29 0x00005555555ddd55 in testing::TestInfo::Run (this=0x5555557275d0) at ../../test/gtest/src/gtest.cc:2861
#30 testing::TestInfo::Run (this=0x5555557275d0) at ../../test/gtest/src/gtest.cc:2833
#31 0x00005555555dde59 in testing::TestSuite::Run (this=0x5555556cf7f0) at ../../test/gtest/src/gtest.cc:3015
#32 testing::TestSuite::Run (this=0x5555556cf7f0) at ../../test/gtest/src/gtest.cc:2993
#33 0x00005555555dfa64 in testing::internal::UnitTestImpl::RunAllTests (this=0x5555556320b0) at ../../test/gtest/src/gtest.cc:5855
```

**Comment by Sherry-Lin** [comment]
Thanks for reporting this issue. We are trying to isolate the culprit change. Please stay tuned.

**Comment by Jexu** [comment]
Could you help try above fix in media driver?

**Comment by stolk** [comment]
Yes, [the fix worked](https://github.com/intel/media-driver/pull/1496#pullrequestreview-1114400361) and unit test is now fast.
